# Generated by Django 3.0.4 on 2020-04-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SynerD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOf', models.CharField(max_length=200)),
                ('typerefID', models.IntegerField()),
                ('subID', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('duedate', models.DateField()),
                ('frequency', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.IntegerField()),
                ('servicecode', models.CharField(max_length=200)),
                ('occurdate', models.DateField()),
                ('subscriberaffected', models.CharField(max_length=200)),
                ('submittedby', models.IntegerField()),
                ('submitdate', models.DateField()),
                ('typeOf', models.CharField(max_length=200)),
                ('approved', models.BooleanField()),
                ('decisiondate', models.DateField()),
                ('decisionstatement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeID', models.IntegerField()),
                ('feename', models.CharField(max_length=200)),
                ('servicecode', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officename', models.CharField(max_length=200)),
                ('officecode', models.CharField(max_length=200)),
                ('attribution', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriberID', models.IntegerField()),
                ('officecode', models.CharField(max_length=200)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgcode', models.CharField(max_length=200)),
                ('orgname', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('datejoined', models.DateField()),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zipcode', models.TextField()),
                ('phonenumber', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgcode', models.CharField(max_length=200)),
                ('subscriberID', models.IntegerField()),
                ('membershipstartdate', models.DateField()),
                ('membershipenddate', models.DateField()),
                ('nativecountry', models.CharField(max_length=200)),
                ('citizenship', models.CharField(max_length=200)),
                ('isdelegate', models.BooleanField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentID', models.IntegerField()),
                ('contributionID', models.IntegerField()),
                ('amountreceived', models.DecimalField(decimal_places=5, max_digits=10)),
                ('receiveddate', models.DateField()),
                ('paymentmethod', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicecode', models.CharField(max_length=200)),
                ('servicename', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('premium', models.CharField(max_length=200)),
                ('allocation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriberID', models.IntegerField()),
                ('servicecode', models.CharField(max_length=200)),
                ('subscriptionrequestdate', models.DateField()),
                ('subscriptionstartdate', models.DateField()),
                ('subscriptionenddate', models.DateField()),
                ('motifofcancellation', models.CharField(max_length=200)),
                ('subscriptiontype', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('beneficiaryID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptiontypecode', models.CharField(max_length=200)),
                ('subscriptiontypename', models.CharField(max_length=200)),
            ],
        ),
    ]
